In [3]:
import torch
data = [[1,2],[3,4]]
test = torch.tensor(data)
test

tensor([[1, 2],
        [3, 4]])

In [5]:
import torch
import numpy as np
data =[[1,2],[3,4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [7]:
import torch
data = [[1,2],[3,4]]
test = torch.tensor(data)
test

x_ones = torch.ones_like(test)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(test,dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4685, 0.8625],
        [0.0418, 0.7933]]) 



In [9]:
import torch

shape =(2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0808, 0.0461, 0.8089],
        [0.2158, 0.2288, 0.1921]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor:{tensor.dtype}")
print(f"Device tensor is stored on : {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on : cpu


In [15]:
import torch 

tensor_1= torch.tensor([[1,2,3,4]])
tensor_2 =  torch.tensor([[5,6,7,8]])
print(torch.cat([tensor_1,tensor_2],dim=0))
print(torch.cat([tensor_1,tensor_2],dim=1))

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])


In [17]:
import torch
tensor = torch.randn(4,4)

print(tensor)
print(f"第一行：{tensor[0]}")
print(f"第一列：{tensor[:,0]}")
print(f"最后一列：{tensor[...,-1]}")

tensor[:,1] = 0
print(tensor)

tensor([[-0.4967,  1.8254,  1.0249,  1.3629],
        [-0.1706, -0.0226, -0.0363,  0.9556],
        [-1.2539, -2.2185, -0.3704,  0.6949],
        [ 1.0122,  1.8648,  0.9358, -0.4784]])
第一行：tensor([-0.4967,  1.8254,  1.0249,  1.3629])
第一列：tensor([-0.4967, -0.1706, -1.2539,  1.0122])
最后一列：tensor([ 1.3629,  0.9556,  0.6949, -0.4784])
tensor([[-0.4967,  0.0000,  1.0249,  1.3629],
        [-0.1706,  0.0000, -0.0363,  0.9556],
        [-1.2539,  0.0000, -0.3704,  0.6949],
        [ 1.0122,  0.0000,  0.9358, -0.4784]])


In [2]:
from PIL import Image
from torchvision import transforms
image_path = r'D:\桌面\ccc.jpg'
image = Image.open(image_path)

transform = transforms.ToTensor()
tensor_image = transform(image)

print(type(tensor_image))

<class 'torch.Tensor'>


In [4]:
import torch
from torchvision import transforms

tensor_image = torch.randn((3,224,224))
transformed_image = transforms.ToPILImage()(tensor_image)

save_path = r'hhh.jpg'

transformed_image.save(save_path)